### ISSUE TITLE
请问一下，CodePush.notifyAppReady() 的调用时机是在什么时候呀

### ISSUE THREAD

**Issue by baixjian** [thundersdata-frontend/td-design#724]
<img width="1153" alt="image" src="https://github.com/thundersdata-frontend/td-design/assets/109275788/3273833d-4d32-4907-9135-ab8b67aedc0d">

**Comment by chj-damon** [comment]
看文档： https://learn.microsoft.com/en-us/appcenter/distribution/codepush/rn-api-ref
[notifyAppReady](https://learn.microsoft.com/en-us/appcenter/distribution/codepush/rn-api-ref#codepushnotifyappready): Notifies the CodePush runtime that an installed update is considered successful. If you're manually checking for and installing updates (that isn't using the [sync](https://learn.microsoft.com/en-us/appcenter/distribution/codepush/rn-api-ref#codepushsync) method to handle it all for you), then this method MUST be called; otherwise CodePush will treat the update as failed and roll back to the previous version when the app next restarts.
